### ISSUE TITLE
Debian ITP

### ISSUE THREAD

**Issue by kenhys** [takaswie/hinawa-utils#1]
Steps to release on debian

* [x] Send ITP E-mail to bugs.d.o
* [x] Release hinawa-utils
* [x] Fix debian/* for official release
* [x] Prepare repository for salsa.d.o
* [x] Upload to mentors.d.n
* [x] Send RFS E-mail to bugs.d.o

**Comment by kenhys** [comment]
I've commented to debian packaging.

https://github.com/takaswie/hinawa-utils/commit/d50d21e169553e5619ac8521b61c31594d2c0b9d

**Comment by takaswie** [comment]
Thank you. I created a commit (2b92f417d858) to add changes according to your advices, then force-pushed to topic/packaging.
https://github.com/takaswie/hinawa-utils/tree/topic/packaging

IMO, it's time to ITP. Would I ask you to send e-mail to bugs.d.o?

**Comment by takaswie** [comment]
I create a milestone for v0.1.0 release. The release will come August 20, 2018.

**Comment by kenhys** [comment]
Hmm, it seems that hinawa-utils-0.0.99.tar.xz doesn't have hinawa-utils-0.0.99/ directory prefix. Is it intended?

**Comment by takaswie** [comment]
Oops. it's my mistake again...

**Comment by kenhys** [comment]
The following command meets what you want, don't you?

```
python setup.py sdist --formats=xztar
```

**Comment by takaswie** [comment]
I generated release package by git, therefore the package is not the one downloadable in python repositories such as PyPy.

The package was generated by this command:

```
$ git archive --format=tar v0.0.99 | xz > hinawa-utils-0.0.99.tar.xz
```

But it should be:

```
$ git archive --format=tar --prefix=hinawa-utils-0.0.99/ v0.0.99 | xz > hinawa-utils-0.0.99.tar.xz
```

In my opinion, we can generate debian package without the downloadable format of Python distribution, can't we?

**Comment by kenhys** [comment]
I agree with the option that sdist is not `MUST`, but anyway, downloadable archive should be fixed to ITP, at least until RFS. Could I understand what you mean correctly?

**Comment by takaswie** [comment]
> I agree with the option that sdist is not MUST, but anyway, downloadable archive should be fixed to ITP, at least until RFS. Could I understand what you mean correctly?

Yes, and I'm OK for the downloadable and fixed archive for ITP.

Then I have a question; we have an option that ITP for v0.0.99 then release v0.1.0 and update the ITP? In this option, what I should do now is to update v0.0.99 package including top-level directory (roughly!), else I'd like you to wait till 20 Aug because I have a plan [to release v1.0.0 then](https://github.com/takaswie/hinawa-utils/issues/1#issuecomment-411251275).

Thanks.

**Comment by kenhys** [comment]
There is a loose relationship between ITP upstream version and the actual one, but not restricted to.
as ITP is just a  declaration  of "I'm working!", so there is a case that ITP for v0.0.99 and RFS for v0.0.99, or ITP for v0.0.99 and RFS for v0.1.0. It depends on upstream and packager.

**Comment by kenhys** [comment]
I've just sent ITP.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905840

**Comment by takaswie** [comment]
Thank you, and I updated released tar.xz for v0.0.99 with top-level 'hinawa-utils-0.0.99/' directory:
https://github.com/takaswie/hinawa-utils/releases

For this task, I prepared for a script. I should have done it before...
https://github.com/takaswie/practices/blob/master/packaging.sh

**Comment by kenhys** [comment]
I've sent RFS based on 0.0.99 :smile: 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905906

**Comment by kenhys** [comment]
And prepared repository for maintenance with gbp workflow
https://salsa.debian.org/debian/hinawa-utils

**Comment by kenhys** [comment]
Then waiting for a sponsor, processing new queue is required.

**Comment by kenhys** [comment]
I'll close this issue because there is nothing to be done.
