### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by cdd3** [takaswie/hinawa-utils#7]
Hello,
  I'm trying to install this library so I can build the snd-firewire-ctl-services package.  when I run cargo install I'm getting the following error.   What am I doing wrong?

$ git clone https://github.com/takaswie/hinawa-utils.git
$ cd hinawa-utils/
$ chmod u+x setup.py
$ ./setup.py
import-im6.q16: unable to open X server ' @ error/import.c/ImportImageCommand/346. ./setup.py: line 6: syntax error near unexpected token ('
./setup.py: line 6: `with open("README", "r") as fh:'

Thanks,
David

**Comment by cdd3** [comment]
So I tried : 

$ git clone https://github.com/takaswie/hinawa-utils.git
$ cd hinawa-utils/
$ chmod u+x setup.py
$ ./setup.py
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/346.
./setup.py: line 6: syntax error near unexpected token `('
./setup.py: line 6: `with open("README", "r") as fh:'

**Comment by takaswie** [comment]
Hi,

> Hello, I'm trying to install this library so I can build the snd-firewire-ctl-services package. when I run cargo install I'm getting the following error. What am I doing wrong?
> 
> $ git clone https://github.com/takaswie/hinawa-utils.git $ cd hinawa-utils/ $ chmod u+x setup.py $ ./setup.py import-im6.q16: unable to open X server ' @ error/import.c/ImportImageCommand/346. ./setup.py: line 6: syntax error near unexpected token (' ./setup.py: line 6: `with open("README", "r") as fh:'
> 
> Thanks, David

Thanks for your filing the issue.

I've never seen such error for installation of hinawa-utils, however included scripts are just available by direct execution without the installation as long as your system has [libhinawa](https://github.com/alsa-project/libhinawa) and [PyGObject](https://pygobject.readthedocs.io/en/latest/).

By the way, what to install for snd-firewire-ctl-services is libhinawa? It seems to have any misunderstanding about dependencies.

Cheers.

**Comment by takaswie** [comment]
Let me close it since getting no reactions.
