### ISSUE TITLE
Apogee Duet problems

### ISSUE THREAD

**Issue by bmtwl** [takaswie/hinawa-utils#8]
Problem with hinawa_utils/oxfw/apogee_protocol.py

fixed execution of hinawa-apogee-duet-cli with the following diff:

274c274
<     def get_meters(cls, fcp: Hinawa.FwFcp):
---
>     def get_meters(cls, unit: Hinawa.FwUnit):
422c422
<     def get_meters(cls, fcp: Hinawa.FwFcp):
---
>     def get_meters(cls, unit: Hinawa.FwUnit):

But even though most functions now work, still can't execute mixer-meters or input-meters, so something fundamental is still broken

**Comment by takaswie** [comment]
Hi @briantolko ,

Thanks for the report, while hinawa-utils project has already abandoned. I' like you to test https://github.com/alsa-project/snd-firewire-ctl-services instead.

Cheers.
